/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warteg;

import java.awt.Dimension;
import java.beans.PropertyVetoException;

/**
 *
 * @author Aziz
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        setLocationRelativeTo(null);
        
        LoginForm login = new LoginForm();
        Dimension desktopSize = MainDekstop.getSize();
        Dimension loginPage = login.getSize();
        login.setLocation((desktopSize.width - loginPage.width)/2,(desktopSize.height- loginPage.height)/2);
        MainDekstop.add(login).setVisible(true);
        
        
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainDekstop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMLogin = new javax.swing.JMenuItem();
        JMLogout = new javax.swing.JMenuItem();
        JMExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout MainDekstopLayout = new javax.swing.GroupLayout(MainDekstop);
        MainDekstop.setLayout(MainDekstopLayout);
        MainDekstopLayout.setHorizontalGroup(
            MainDekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        MainDekstopLayout.setVerticalGroup(
            MainDekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        JMLogin.setText("Login");
        JMLogin.setEnabled(false);
        JMLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMLoginActionPerformed(evt);
            }
        });
        jMenu1.add(JMLogin);

        JMLogout.setText("Logout");
        JMLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(JMLogout);

        JMExit.setText("Exit");
        JMExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMExitActionPerformed(evt);
            }
        });
        jMenu1.add(JMExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainDekstop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainDekstop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMLoginActionPerformed
        LoginForm login = new LoginForm();
        Dimension desktopSize = MainDekstop.getSize();
        Dimension loginPage = login.getSize();
        login.setLocation((desktopSize.width - loginPage.width)/2,(desktopSize.height- loginPage.height)/2);
        MainDekstop.add(login).setVisible(true);
        
        JMLogout.setEnabled(true);
    }//GEN-LAST:event_JMLoginActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
       
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void JMLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMLogoutActionPerformed
        MainDekstop.removeAll();
        LoginForm login = new LoginForm();
        PemesananForm pesanan = new PemesananForm();
        pesanan.setVisible(false);
        
        Dimension pesananPage = pesanan.getSize();
        Dimension desktopSize = MainDekstop.getSize();
        Dimension loginPage = login.getSize();
        login.setLocation((desktopSize.width - loginPage.width)/2,(pesananPage.height- loginPage.height)/2);
        MainDekstop.add(login).setVisible(true);
        
        
        JMLogout.setEnabled(false);
    }//GEN-LAST:event_JMLogoutActionPerformed

    private void JMExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMExit;
    private javax.swing.JMenuItem JMLogin;
    private javax.swing.JMenuItem JMLogout;
    private javax.swing.JDesktopPane MainDekstop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
