/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warteg;

import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Aziz
 */
public class PemesananForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form PemesananForm
     */
    public PemesananForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTMeja = new javax.swing.JTextField();
        JBProses = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        JCPaket1 = new javax.swing.JComboBox<>();
        JCPaket2 = new javax.swing.JComboBox<>();
        JCPaket3 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTHarga1 = new javax.swing.JTextField();
        JTBeli1 = new javax.swing.JTextField();
        JTBayar1 = new javax.swing.JTextField();
        JTBayar2 = new javax.swing.JTextField();
        JTBeli2 = new javax.swing.JTextField();
        JTHarga2 = new javax.swing.JTextField();
        JTHarga3 = new javax.swing.JTextField();
        JTBeli3 = new javax.swing.JTextField();
        JTBayar3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        JTTotal = new javax.swing.JTextField();
        JBBayar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PEMESANAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No. Meja :");

        JTMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTMejaActionPerformed(evt);
            }
        });

        JBProses.setBackground(new java.awt.Color(102, 102, 102));
        JBProses.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        JBProses.setForeground(new java.awt.Color(255, 255, 255));
        JBProses.setText("Proses");
        JBProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBProsesActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        JCPaket1.setBackground(new java.awt.Color(0, 51, 255));
        JCPaket1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        JCPaket1.setForeground(new java.awt.Color(255, 255, 255));
        JCPaket1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAKET 1", "Nasi Putih", "Nasi Goreng", "Nasi Capacay" }));
        JCPaket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCPaket1ActionPerformed(evt);
            }
        });

        JCPaket2.setBackground(new java.awt.Color(0, 51, 255));
        JCPaket2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        JCPaket2.setForeground(new java.awt.Color(255, 255, 255));
        JCPaket2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAKET 2", "Ayam Penyet", "Ayam Bakar", "Ayam Goreng" }));
        JCPaket2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCPaket2ActionPerformed(evt);
            }
        });

        JCPaket3.setBackground(new java.awt.Color(0, 51, 255));
        JCPaket3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        JCPaket3.setForeground(new java.awt.Color(255, 255, 255));
        JCPaket3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAKET 3", "Aqua", "Jus Alpukat", "Jus Jeruk" }));
        JCPaket3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCPaket3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Harga");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bayar");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Juml.Beli");

        JTHarga1.setEditable(false);
        JTHarga1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JTBeli1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JTBeli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBeli1ActionPerformed(evt);
            }
        });
        JTBeli1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTBeli1KeyReleased(evt);
            }
        });

        JTBayar1.setEditable(false);
        JTBayar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTBayar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBayar1ActionPerformed(evt);
            }
        });

        JTBayar2.setEditable(false);
        JTBayar2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        JTBeli2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JTBeli2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTBeli2KeyReleased(evt);
            }
        });

        JTHarga2.setEditable(false);
        JTHarga2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JTHarga3.setEditable(false);
        JTHarga3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JTBeli3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JTBeli3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTBeli3KeyReleased(evt);
            }
        });

        JTBayar3.setEditable(false);
        JTBayar3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TOTAL PESANAN");

        JTTotal.setEditable(false);
        JTTotal.setBackground(new java.awt.Color(102, 102, 102));
        JTTotal.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        JTTotal.setForeground(new java.awt.Color(0, 51, 204));
        JTTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JCPaket1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JTHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(JTBeli1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(JTBayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(78, 78, 78))))
            .addComponent(jSeparator3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JCPaket2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JTHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(JTBeli2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JCPaket3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JTHarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(JTBeli3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTBayar2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(JTBayar3))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTHarga1)
                    .addComponent(JCPaket1)
                    .addComponent(JTBeli1)
                    .addComponent(JTBayar1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTBeli2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JCPaket2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JTBayar2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JTBeli3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JTHarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JTBayar3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JCPaket3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(JTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        JBBayar.setBackground(new java.awt.Color(102, 102, 102));
        JBBayar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        JBBayar.setForeground(new java.awt.Color(255, 255, 255));
        JBBayar.setText("BAYAR");
        JBBayar.setEnabled(false);
        JBBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JBBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(JTMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBProses, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBProses, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBBayar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTMejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTMejaActionPerformed

    private void JBBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBayarActionPerformed
        PembayaranForm pembayaran = new PembayaranForm(JTMeja.getText(), JTTotal.getText());
        JDesktopPane MainDekstop = getDesktopPane();
        
        Dimension desktopSize = MainDekstop.getSize();
        Dimension bayar = pembayaran.getSize();
        pembayaran.setLocation((desktopSize.width - bayar.width)/2,(desktopSize.height- bayar.height)/2);
        MainDekstop.add(pembayaran).setVisible(true);
    }//GEN-LAST:event_JBBayarActionPerformed

    private void JTTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTTotalActionPerformed

    private void JCPaket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCPaket1ActionPerformed
        switch (JCPaket1.getSelectedIndex()) {
            case 1:
                JTHarga1.setText("3000");
                break;
            case 2:
                JTHarga1.setText("12000");
                break;
            case 3:
                JTHarga1.setText("10000");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_JCPaket1ActionPerformed

    private void JCPaket2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCPaket2ActionPerformed
               switch (JCPaket2.getSelectedIndex()) {
            case 1:
                JTHarga2.setText("14000");
                break;
            case 2:
                JTHarga2.setText("13500");
                break;
            case 3:
                JTHarga2.setText("12000");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_JCPaket2ActionPerformed

    private void JCPaket3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCPaket3ActionPerformed
         switch (JCPaket3.getSelectedIndex()) {
            case 1:
                JTHarga3.setText("1000");
                break;
            case 2:
                JTHarga3.setText("7000");
                break;
            case 3:
                JTHarga3.setText("7000" );
                break;
            default:
                break;
        }
    }//GEN-LAST:event_JCPaket3ActionPerformed

    private void JTBeli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBeli1ActionPerformed

        
    }//GEN-LAST:event_JTBeli1ActionPerformed

    private void JTBeli1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTBeli1KeyReleased
        if(JCPaket1.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Pilih Menu PAKET", "Error", JOptionPane.ERROR_MESSAGE);
            JCPaket1.requestFocus();
            JTBeli1.setText("");
        }
        int jmlBeli = Integer.parseInt(JTBeli1.getText());
        int harga = Integer.parseInt(JTHarga1.getText());
        int total = (jmlBeli * harga);
        
        JTBayar1.setText("" + total);
    }//GEN-LAST:event_JTBeli1KeyReleased

    private void JTBeli2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTBeli2KeyReleased
        if(JCPaket2.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Pilih Menu PAKET", "Error", JOptionPane.ERROR_MESSAGE);
            JCPaket2.requestFocus();
            JTBeli2.setText("");
        }        
        int jmlBeli = Integer.parseInt(JTBeli2.getText());
        int harga = Integer.parseInt(JTHarga2.getText());
        int total = (jmlBeli * harga);
        
        JTBayar2.setText("" + total);
    }//GEN-LAST:event_JTBeli2KeyReleased

    private void JTBeli3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTBeli3KeyReleased
        if(JCPaket3.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Pilih Menu PAKET", "Error", JOptionPane.ERROR_MESSAGE);
            JCPaket3.requestFocus();
            JTBeli3.setText("");
        }
        int jmlBeli = Integer.parseInt(JTBeli3.getText());
        int harga = Integer.parseInt(JTHarga3.getText());
        int total = (jmlBeli * harga);
        
        JTBayar3.setText("" + total);
    }//GEN-LAST:event_JTBeli3KeyReleased

    private void JTBayar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBayar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTBayar1ActionPerformed

    private void JBProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBProsesActionPerformed
        int total1 = Integer.parseInt(JTBayar1.getText());
        int total2 = Integer.parseInt(JTBayar2.getText());
        int total3 = Integer.parseInt(JTBayar3.getText());
        
        int jumlah = (total1 + total2 + total3);
        
        JTTotal.setText(""+ jumlah);
        
        JBBayar.setEnabled(true);
        
        
        
    }//GEN-LAST:event_JBProsesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBayar;
    private javax.swing.JButton JBProses;
    private javax.swing.JComboBox<String> JCPaket1;
    private javax.swing.JComboBox<String> JCPaket2;
    private javax.swing.JComboBox<String> JCPaket3;
    private javax.swing.JTextField JTBayar1;
    private javax.swing.JTextField JTBayar2;
    private javax.swing.JTextField JTBayar3;
    private javax.swing.JTextField JTBeli1;
    private javax.swing.JTextField JTBeli2;
    private javax.swing.JTextField JTBeli3;
    private javax.swing.JTextField JTHarga1;
    private javax.swing.JTextField JTHarga2;
    private javax.swing.JTextField JTHarga3;
    private javax.swing.JTextField JTMeja;
    private javax.swing.JTextField JTTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
